@startuml
'https://plantuml.com/sequence-
participant Connector[
=Connector
----
- Driver: new Chromedriver
- Gui: GUI
- URL: String (String Link (als GUI.SearchBar() nog niet gemaakt is)
- Data: ArrayList <WebElement>
----
+ Connector(GUI gui)
+ Open()
+ Connect(String Link (als GUI.SearchBar() nog niet gemaakt is) / null)
- Collect(): ArrayList <WebElement>
+ Close()
]

participant Writer[
=Writer
----
- file: File
- rightData: RightData
----
+ Writer(RightData rightData)
+ ReadFie()
+ WriteFile()
+ ReturnStatus()
]

participant RightData[
=RightData
----
- connector: Connector
- gui: GUI
- UsedData: ArrayList <String>
- file: File
- Countries: ArrayList <String>
- AllowData: Boolean
----
+ RightData()
+ ScanData()
+ Show()
+ Check(): Boolean
+ ReadFile()
+ UploadFile()
+ getData(): ArrayList <String> UsedData
]

participant GUI[
=GUI
----
- Frame: JFrame
- connector: Connector
- rightData: RightData
----
+ GUI(Connector connector, RightData rightData)
- Window()
- Shower()
- SearchBar(): String
+ UploadButton()
+ SearchButton()
+ ConfirmButton(): Boolean
]

Connector <- GUI: 0.1 Geeft URL-link aan 0
Writer <- RightData: 0.1 Geeft file aan 0
Connector -> RightData: 0.1 Geeft data aan 0
RightData -> GUI: 0.1 Geeft ArrayList aan 0
RightData <- GUI: 1 Geeft toestemming om akoord te gaan met scrijven aan 0
Writer <- RightData: 1 Geeft toestemming om te schrijven aan 0

autonumber
@enduml