@startuml
'https://plantuml.com/sequence-diagram

class ConnectWebsite{
    - driver: Chromedriver
    - gui: GUI
    - URL: String
    - Data: ArrayList<WebElement>

    + Connector(Gui gui)
    + Open()
    + Connect()
    - Collect(): ArrayList<WebElement>
    + Close()
}

class Writer{
    - file: File
    - chekData: CheckData

    + Writer(CheckData checkData)
    + ReadFie()
    + WriteFile()
    + ReturnStatus()
}

class CheckData{
    - ConnectWebsite: Connector
    - gui: GUI
    - file: File
    - AllowData: Boolean
    - UsedData: ArrayList <String>
    - Countries: ArrayList <String>

    + CheckData(Connector connector, Gui gui)
    + ScanData()
    + Show()
    + ReadFile()
    + UploadFile()
    + getData(): ArrayList <String> UsedData
 }

class GUI{
    - Frame: JFrame
    - connector: Connector
    - chekData: CheckData
    - Search: Boolean
    - URL: String

    + GUI(Connector connector, CheckData chekData)
    - Window()
    - Shower()
}

interface IButton{
    + createButton()
    + action()
}

class uploadButton{
    - chekData: CheckData

    + uploadButton(CheckData checkData)
}


class searchButton{
    - connector: ConnectWebsite

    + searchButton(ConnectWebsite connector)
}

class SearchBar{
    - box: JTextField

    + create()
    + action()
}



class SelectFromSheet{
}

class SelectButton{

    + SelectButton(SelectFromSheet)
}

class WriterButton{
    - writer: Writer
    + WriterButton(Writer writer)
    + Confirm()
    + Cancel()
}

IButton ..> uploadButton
IButton ..> WriterButton
IButton ..> searchButton
IButton ..> SelectSheetButton
IButton ..> SelectKeySource


GUI <- SearchBar

CheckData -> GUI

Writer <- CheckData

uploadButton <- CheckData
WriterButton <- Writer
searchButton <- ConnectWebsite

WriterButton <|- uploadButton
WriterButton <|-- searchButton
WriterButton <|-- SelectFromSheetButton

uploadButton -> GUI
WriterButton -> GUI
searchButton -> GUI
SelectFromSheetButton -> GUI

SelectFromSheet --> GUI



@enduml