@startuml
'https://plantuml.com/sequence-
class Connector {
    - Driver: Chromedriver
    - Gui: GUI
    - URL: String
    - Data: ArrayList<WebElement>

    + Connector(GUI gui)
    + Open()
    + Connect(String Link)
    - Collect(): ArrayList<WebElement>
    + Close()
}

class Writer{
    - file: File
    - rightData: RightData

    + Writer(RightData rightData)
    + ReadFie()
    + WriteFile()
    + ReturnStatus()
}

class RightData{
    - connector: Connector
    - gui: GUI
    - UsedData: ArrayList <String>
    - file: File
    - Countries: ArrayList <String>
    - AllowData: Boolean

    + RightData(Connector connector, Gui gui)
    + ScanData()
    + Show()
    + ReadFile()
    + UploadFile()
    + getData(): ArrayList <String> UsedData
 }

class GUI{
    - Frame: JFrame
    - connector: Connector
    - rightData: RightData
    - Search: Boolean
    - URL-link: String

    + GUI(Connector connector, RightData rightData)
    - Window()
    - Shower()
    - SearchBar(): String
    + UploadButton()
    + SearchButton()
    + ConfirmButton(): Boolean
    + GetURL(): String
}

Connector <- GUI: 0.1 Geeft URL-link aan 0
Writer <- RightData: 0.1 Geeft file aan 0
Connector -> RightData: 0.1 Geeft data aan 0
RightData -> GUI: 0.1 Geeft ArrayList aan 0
RightData <- GUI: 1 Geeft een de naam en positie van File door aan 0
Writer <- GUI: 1 Geeft toestemming om  te gaan scrijven 0

@enduml